version: '3'

networks:
    symfony-net:
volumes:
    db-data:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - postgres
        networks:
            - symfony-net
        links:
            - php74-service

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - symfony-net

    postgres:
        container_name: app_postgres
        image: postgres:12.4-alpine
        restart: on-failure
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: sf_user
            POSTGRES_PASSWORD: random_password
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"
        networks:
            - symfony-net
        depends_on:
            - rabbitmq
    
    rabbitmq:
        image: rabbitmq:3.9-management
        ports:
            - '5672:5672'
            - '15672:15672'
        environment:
            - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@rabbitmq:5672/%2f/messages
        networks:
            - symfony-net
    

  